profit_threshold: 0.0001  # in Ether
use_flashbots: true
decoy_transactions_enabled: false
off_peak_hours: [1,2,3,4]
dynamic_gas: true
maxDailyLoss: 1000
circuit_breaker_enabled: true
test_mode: false

fallback_oracles:
  - band
  - uma

ethical_constraints:
  max_slippage: "0.5%"
  blacklisted_pools: []
  min_profit_to_act: 0.0001  # in Ether

liquidity_threshold: "10000000000000000000000"
volatility_threshold: "0.01"
gas_oracle_url: "https://api.blocknative.com/gasprices/v2"
bidding_increment_percentage: "0.05"
max_bidding_attempts: "5"
bid_time_decay_factor: "0.9"
bid_time_decay_interval: 10

max_slippage: 50
